
export const USER_REG_REQUEST = "USER_REG_REQUEST";
export const USER_REG_SUCCESS = "USER_REG_SUCCESS";
export const USER_REG_FAIL = "USER_REG_FAIL";
export const USER_REG_REST = "USER_REG_REST";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";

export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";

export const USER_PROFILE_UPDATE_REQUEST = "USER_PROFILE_UPDATE_REQUEST";
export const USER_PROFILE_UPDATE_SUCCESS = "USER_PROFILE_UPDATE_SUCCESS";
export const USER_PROFILE_UPDATE_FAIL = "USER_PROFILE_UPDATE_FAIL";
export const USER_PROFILE_UPDATE_REST = "USER_PROFILE_UPDATE_REST";


export const USER_FOLLOWING_REQUEST = "USER_FOLLOWING_REQUEST";
export const USER_FOLLOWING_SUCCESS = "USER_FOLLOWING_SUCCESS";
export const USER_FOLLOWING_FAIL = "USER_FOLLOWING_FAIL";


export const USER_FOLLWERS_REQUEST = "USER_FOLLWERS_REQUEST";
export const USER_FOLLWERS_SUCCESS = "USER_FOLLWERS_SUCCESS";
export const USER_FOLLWERS_FAIL = "USER_FOLLWERS_FAIL";


export const USER_FRIENDS_FOLLOWING_REQUEST = "USER_FRIENDS_FOLLOWING_REQUEST";
export const USER_FRIENDS_FOLLOWING_SUCCESS = "USER_FRIENDS_FOLLOWING_SUCCESS";
export const USER_FRIENDS_FOLLOWING_FAIL = "USER_FRIENDS_FOLLOWING_FAIL";


export const USER_FRIENDS_FOLLWERS_REQUEST = "USER_FRIENDS_FOLLWERS_REQUEST";
export const USER_FRIENDS_FOLLWERS_SUCCESS = "USER_FRIENDS_FOLLWERS_SUCCESS";
export const USER_FRIENDS_FOLLWERS_FAIL = "USER_FRIENDS_FOLLWERS_FAIL";



export const USER_TO_FOLLOW_REQUEST = "USER_TO_FOLLOW_REQUEST";
export const USER_TO_FOLLOW_SUCCESS = "USER_TO_FOLLOW_SUCCESS";
export const USER_TO_FOLLOW_FAIL = "USER_TO_FOLLOW_FAIL";

export const USER_TO_UNFOLLOW_REQUEST = "USER_TO_UNFOLLOW_REQUEST";
export const USER_TO_UNFOLLOW_SUCCESS = "USER_TO_UNFOLLOW_SUCCESS";
export const USER_TO_UNFOLLOW_FAIL = "USER_TO_UNFOLLOW_FAIL";

